### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by OMG-Tech** [AmIrReZa386/FIREAC#13]
The whitelist is not working.

I did put in ALL the identifiers that are available in the whitelist file but I'm still getting banned when I use certain things in the txAdmin menu.

**Comment by Zzeyy** [comment]
Oops

**Comment by OMG-Tech** [comment]
?

**Comment by AmIrReZa386** [comment]
I check it now

**Comment by AmIrReZa386** [comment]
Yes it's true
I release new version now

**Comment by OMG-Tech** [comment]
Alright, thank you!

**Comment by AmIrReZa386** [comment]
I released check and report me it's fix or not
if not
I check it again

**Comment by OMG-Tech** [comment]
Its still not working, I gave myself all weapons with the FIREAC admin menu and I got banned

**Comment by AmIrReZa386** [comment]
okey i check it again

**Comment by OMG-Tech** [comment]
Alright, thank you
________________________________

**Comment by AmIrReZa386** [comment]
Whitelist is now fixed !
thanks
